// The frozen daily archive: which questions each daily #N asks. Generated by scripts/build-daily.mjs.
import type { ModeId } from './session'

export interface DailyArchive {
  epoch: string
  rotation: ModeId[]
  days: string[][]
}

let cache: Promise<DailyArchive | null> | null = null

export function loadArchive(): Promise<DailyArchive | null> {
  if (!cache) {
    cache = fetch(`${import.meta.env.BASE_URL}data/daily.json`)
      .then((r) => (r.ok ? (r.json() as Promise<DailyArchive>) : null))
      .catch(() => null)
    cache.then((a) => {
      if (!a) cache = null
    })
  }
  return cache
}

/** Frozen picks of daily #n, or null when the archive is missing or does not reach that far. */
export function picksFor(archive: DailyArchive | null, n: number): string[] | null {
  const day = archive?.days[n - 1]
  return day && day.length ? day : null
}
