"""Download the web fonts from Google Fonts once and self-host them in public/fonts (needed for offline play).

Usage: python scripts/fetch-fonts.py
Writes public/fonts/*.woff2 and src/fonts.css
"""
import os, re, subprocess, urllib.parse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "public", "fonts")
os.makedirs(OUT, exist_ok=True)
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
FAMILIES = ["Overpass:wght@700;800;900", "Barlow:wght@400;500;600;700", "Barlow+Condensed:wght@600;700;800"]

url = "https://fonts.googleapis.com/css2?" + "&".join("family=" + f for f in FAMILIES) + "&display=swap"
css = subprocess.run(["curl", "-s", "-A", UA, url], capture_output=True, text=True).stdout
blocks = re.findall(r"/\* (\w+) \*/\s*@font-face \{(.*?)\}", css, re.S)
out = []
for subset, body in blocks:
    if subset != "latin":
        continue
    family = re.search(r"font-family: '([^']+)'", body).group(1)
    weight = re.search(r"font-weight: (\d+)", body).group(1)
    src = re.search(r"url\((https://[^)]+)\)", body).group(1)
    name = f"{family.replace(' ', '')}-{weight}.woff2"
    path = os.path.join(OUT, name)
    if not os.path.exists(path):
        subprocess.run(["curl", "-sL", "-A", UA, "-o", path, src])
    out.append(f"@font-face {{\n  font-family: '{family}';\n  font-style: normal;\n  font-weight: {weight};\n  font-display: swap;\n  src: url('/fonts/{name}') format('woff2');\n}}")
    print("font", name, os.path.getsize(path), "bytes")
open(os.path.join(ROOT, "src", "fonts.css"), "w").write("/* Generated by scripts/fetch-fonts.py. Self-hosted so the game works offline. */\n" + "\n".join(out) + "\n")
print("wrote src/fonts.css with", len(out), "faces")
